export const templates = [
  {
    id: 'stockholm',
    name: 'Stockholm',
    layout: 'single-column',
    primaryColor: '#1e293b',
    accentColor: '#475569',
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'standard',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    layout: 'two-column',
    primaryColor: '#2563eb',
    accentColor: '#3b82f6',
    fontHeading: "'Roboto', sans-serif",
    fontBody: "'Roboto', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'solid-bg', // meaning sidebar will have a solid bg
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    layout: 'single-column',
    primaryColor: '#db2777',
    accentColor: '#f43f5e',
    fontHeading: "'Poppins', sans-serif",
    fontBody: "'Poppins', sans-serif",
    headerAlignment: 'center',
    headerStyle: 'minimal',
  },
  {
    id: 'madrid',
    name: 'Madrid',
    layout: 'two-column',
    primaryColor: '#0f766e',
    accentColor: '#14b8a6',
    fontHeading: "'Georgia', serif",
    fontBody: "'Georgia', serif",
    headerAlignment: 'left',
    headerStyle: 'standard',
  },
  {
    id: 'dublin',
    name: 'Dublin',
    layout: 'timeline',
    primaryColor: '#b45309',
    accentColor: '#d97706',
    fontHeading: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    fontBody: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    headerAlignment: 'left',
    headerStyle: 'minimal',
  },
  {
    id: 'vienna',
    name: 'Vienna',
    layout: 'single-column',
    primaryColor: '#4338ca',
    accentColor: '#6366f1',
    fontHeading: "'Playfair Display', serif",
    fontBody: "'Lato', sans-serif",
    headerAlignment: 'center',
    headerStyle: 'standard',
  },
  {
    id: 'london',
    name: 'London',
    layout: 'two-column',
    primaryColor: '#1e1e1e',
    accentColor: '#737373',
    fontHeading: "'Oswald', sans-serif",
    fontBody: "'Open Sans', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'minimal',
  },
  {
    id: 'rome',
    name: 'Rome',
    layout: 'timeline',
    primaryColor: '#b91c1c',
    accentColor: '#dc2626',
    fontHeading: "'Merriweather', serif",
    fontBody: "'Merriweather', serif",
    headerAlignment: 'center',
    headerStyle: 'standard',
  },
  {
    id: 'toronto',
    name: 'Toronto',
    layout: 'single-column',
    primaryColor: '#1d4ed8',
    accentColor: '#2563eb',
    fontHeading: "'Montserrat', sans-serif",
    fontBody: "'Montserrat', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'minimal',
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    layout: 'two-column',
    primaryColor: '#0369a1',
    accentColor: '#0ea5e9',
    fontHeading: "'Source Sans Pro', sans-serif",
    fontBody: "'Source Sans Pro', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'solid-bg',
  },
  {
    id: 'paris',
    name: 'Paris',
    layout: 'single-column',
    primaryColor: '#4c1d95',
    accentColor: '#7c3aed',
    fontHeading: "'Cormorant Garamond', serif",
    fontBody: "'Proxima Nova', sans-serif",
    headerAlignment: 'center',
    headerStyle: 'standard',
  },
  {
    id: 'newyork',
    name: 'New York',
    layout: 'timeline',
    primaryColor: '#111827',
    accentColor: '#374151',
    fontHeading: "'Bebas Neue', sans-serif",
    fontBody: "'Roboto', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'minimal',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    layout: 'two-column',
    primaryColor: '#be123c',
    accentColor: '#e11d48',
    fontHeading: "'Noto Sans', sans-serif",
    fontBody: "'Noto Sans', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'standard',
  },
  {
    id: 'berlin',
    name: 'Berlin',
    layout: 'single-column',
    primaryColor: '#b45309',
    accentColor: '#f59e0b',
    fontHeading: "'Ubuntu', sans-serif",
    fontBody: "'Ubuntu', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'standard',
  },
  {
    id: 'geneva',
    name: 'Geneva',
    layout: 'two-column',
    primaryColor: '#3f6212',
    accentColor: '#65a30d',
    fontHeading: "'Raleway', sans-serif",
    fontBody: "'Raleway', sans-serif",
    headerAlignment: 'center',
    headerStyle: 'minimal',
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    layout: 'timeline',
    primaryColor: '#0f766e',
    accentColor: '#0d9488',
    fontHeading: "'PT Serif', serif",
    fontBody: "'PT Sans', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'standard',
  },
  {
    id: 'prague',
    name: 'Prague',
    layout: 'single-column',
    primaryColor: '#334155',
    accentColor: '#475569',
    fontHeading: "'Lora', serif",
    fontBody: "'Lora', serif",
    headerAlignment: 'center',
    headerStyle: 'minimal',
  },
  {
    id: 'oslo',
    name: 'Oslo',
    layout: 'two-column',
    primaryColor: '#1e3a8a',
    accentColor: '#1d4ed8',
    fontHeading: "'Nunito', sans-serif",
    fontBody: "'Nunito', sans-serif",
    headerAlignment: 'left',
    headerStyle: 'solid-bg',
  }
];

export const getTemplateById = (id) => {
  return templates.find((t) => t.id === id) || templates[0];
};
